# All manifests relevnat to this policy should be in this file. This include the policy definition, exceptions, reports etc
{{- if .Values.opsPolicies.disallowNodePortService.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-nodeport
  annotations:
    policies.kyverno.io/title: Disallow NodePort
    policies.kyverno.io/category: Ops, Best Practices
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Service
    policies.kyverno.io/description: >-
      A Kubernetes Service of type NodePort uses a host port to receive traffic from
      any source. A NetworkPolicy cannot be used to control traffic to host ports.
      Although NodePort Services can be useful, their use must be limited to Services
      with additional upstream security checks. This policy validates that any new Services
      do not use the `NodePort` type.
spec:
  background: true
  webhookConfiguration:
    timeoutSeconds: 30
  rules:
  - name: validate-nodeport
    match:
      any:
      - resources:
          kinds:
          - Service
    validate:
      failureAction: {{ .Values.opsPolicies.disallowNodePortService.mode }} 
      message: "Services of type NodePort are not allowed."
      pattern:
        spec:
          =(type): "!NodePort"

{{- end }}
