global:
  resolve_timeout: 5m
  slack_api_url: ""

templates:
- '/etc/alertmanager-templates/*.tmpl'
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 5m  
  receiver: default 
  routes:
  - match:
      team: devops
    receiver: devops
    continue: true 
  - match: 
      team: dev
    receiver: dev
    continue: true
  - match: 
      team: slack
    receiver: slack
    continue: true

receivers:
- name: 'default'

- name: 'devops'
  slack_configs:
  - channel: '#k8s-alerting'
    send_resolved: true
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    text: " \nSummary: {{ .CommonAnnotations.summary }}\nDescription: {{ .CommonAnnotations.description }} "

- name: 'dev'
  slack_configs:
  - channel: '#k8s-alerting'
    send_resolved: true
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    text: " \nSummary: {{ .CommonAnnotations.summary }}\nDescription: {{ .CommonAnnotations.description }} "

- name: 'slack'
  slack_configs:
  - channel: '#k8s-alerting'
    send_resolved: true
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    text: " \nSummary: {{ .CommonAnnotations.summary }}\nDescription: {{ .CommonAnnotations.description }} "
