{{- if .Values.elasticExporter.enabled -}}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: es-exporter
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    es_uri: {{ .Values.elasticExporter.es.uri }} 
  template:
    metadata:
      name: es-exporter
      namespace: {{ .Values.namespace }}
    type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-exporter
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: elastic-exporter
  template:
    metadata:
      labels:
        app: elastic-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9114"
    spec:
      containers:
      - command:
        - /bin/elasticsearch_exporter
        - --es.ssl-skip-verify
        - '--es.all'
        - '--collector.clustersettings'
        - '--es.uri=$(ES_URI)'
      {{- range .Values.elasticExporter.extraArgs }}
        - '--{{ . }}'
      {{- end }}
        image: {{ .Values.elasticExporter.image }}
        env:
        - name: ES_URI
          valueFrom:
            secretKeyRef:
              name: es-exporter
              key: es_uri 
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9114
          initialDelaySeconds: 30
          timeoutSeconds: 10
        name: elastic-exporter
        ports:
        - containerPort: 9114
          name: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9114
          initialDelaySeconds: 10
          timeoutSeconds: 10
        resources:
          {{- toYaml .Values.elasticExporter.resources | nindent 12 }}
      restartPolicy: Always
{{- end }}
