{{- if .Values.grafana.dashboards.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  name: grafana-dashboards
  labels:
    name: grafana-dashboards
  namespace: {{ .Values.namespace }}
data:
  dashboards.yaml: |-
{{ .Files.Get "configs/grafana-dashboard.yaml" | indent 4 }}
{{- (.Files.Glob "configs/grafana-dashboards/**.json").AsConfig | nindent 2 }}
{{- end }}
