{{- if .Values.grafana.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-conf
  labels:
    name: grafana-datasource-conf
  namespace: {{ .Values.namespace }}
data:
  datasources.yaml: |-
{{ .Files.Get "configs/grafana-datasource.yaml" | indent 4 }}
{{- end }}
