{{- if .Values.grafana.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.grafana.httpRoute.gatewayName }}
      namespace: envoy-gateway-system
      sectionName: https
  hostnames:
  - {{ .Values.grafana.httpRoute.host }}
  rules:
    - backendRefs:
        - name: grafana
          port: 3000
      matches:
        - path:
            type: PathPrefix
            value: /

{{- end }}