apiVersion: v1
kind: ServiceAccount
metadata:
  name: spinnaker
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: spinnaker
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
