apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  labels:
    name: prometheus-rules
  namespace: {{ .Values.namespace }}
data:
  alert-rules.yaml: |-
{{ .Values.prometheus.rules.config | indent 4 }}
