{{- if .Values.internalGateway.enable -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal-eg-infra-shared-01
  namespace: {{ .Values.namespace }}
spec:
  gatewayClassName: infra-shared-01
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: internal-custom-proxy-config
  listeners:
    - allowedRoutes:
        namespaces:
          from: All
      hostname: '{{ .Values.internalGateway.defaultHttps.hostname }}'
      name: https
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
        - group: ""
          kind: Secret
          name: {{ .Values.internalGateway.defaultHttps.certSecretName }}
          namespace: {{ .Values.namespace }}
    {{- if .Values.internalGateway.extraListeners }}
    {{- toYaml .Values.internalGateway.extraListeners | nindent 4 }}
    {{- end }}
---
{{- end }}
