apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-redirect-https-external
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
    - name: eg-infra-shared-01
      kind: Gateway
      group: gateway.networking.k8s.io
      namespace: {{ .Values.namespace }}
      port: 80
      sectionName: http
  rules:
    - filters:
      - type: RequestRedirect
        requestRedirect:
          scheme: https
          statusCode: 301
          port: 443
      matches:
        - path:
            type: PathPrefix
            value: /
