cluster:
  env: ops
  name: ops-01
  server: https://ops-01-k8s.endpoint.kubernetes

source:
  targetRevision: stable # this can be a git branch, commit or a tag
  helm:
    valueFiles: values.ops-01.yaml

sealedSecrets:  # targetRevision and valueFiles can be overridden here if the above defaults are not suitable
  enable: true

envoyGateway:
  enable: true

externalDNS:
  enable: true

certManager:
  enable: true

monitoring:
  enable: true

logging:
  enable: true

jaeger:
  enable: true

kyverno:
  enable: true

redis:
  enable: true
