cluster:
  name: ops-01
  server: https://kubernetes.default.svc

source:
  targetRevision: HEAD # this can be a git branch, commit or a tag
  helm:
    valueFiles: values.ops-01.yaml

sealedSecrets:  # targetRevision and valueFiles can be overridden here if the above defaults are not suitable
  enable: true

envoyGateway:
  enable: true

monitoring:
  enable: true

logging:
  enable: true

kyverno:
  enable: true

redis:
  enable: true
