cluster:
  name: dev-01
  server: dev-k8s.endpoint.kubernetes

source:
  targetRevision: staging
  helm:
    valueFiles: values.stag.yaml

sealedSecrets:
  enable: true

ingressController:
  enable: true

