cluster:
  name: ops-01
  server: ops-01-k8s.endpoint.kubernetes

source:
  targetRevision: HEAD
  helm:
    valueFiles: values.ops-01.yaml

sealedSecrets:
  enable: true

ingressController:
  enable: true

monitoring:
  enable: true
