cluster:
  name: ops-01
  server: https://kubernetes.default.svc

source:
  targetRevision: HEAD
  helm:
    valueFiles: values.ops-01.yaml

sealedSecrets:
  enable: true

ingressController:
  enable: true

monitoring:
  enable: true
