{{- if .Values.alertmanager.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
  namespace: {{ .Values.namespace }}
data:
  config.yml: |-
{{ .Files.Get "configs/alertmanager-config.yaml" | indent 4 }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: {{ .Values.namespace }}
  labels:
    app: alertmanager
spec:
  replicas: 0
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: {{ .Values.alertmanager.image }}
        args:
          - '--config.file=/etc/alertmanager/config.yml'
          - '--storage.path=/alertmanager'
        ports:
        - name: alertmanager
          containerPort: 9093
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
        - name: alertmanager
          mountPath: /alertmanager
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager
      - name: alertmanager
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
  labels:
    name: alertmanager
  name: alertmanager
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: alertmanager
  type: {{ .Values.alertmanager.service.type }}
  ports:
  - name: alertmanager
    protocol: TCP
    port: 9093
    targetPort: 9093
{{- end }}
