apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: {{ .Values.namespace }}
spec:
  telemetry:
    metrics:
      prometheus: {}
  provider:
    type: Kubernetes
    kubernetes:
    {{- if .Values.proxyConfig.service.annotations }} 
      envoyService:
        annotations:
        {{- with .Values.proxyConfig.service.annotations }}
        {{- toYaml . | nindent 10 }}
        {{- end }}
    {{- end }}
      envoyDeployment:
        patch:
          type: StrategicMerge
          value:
            spec:
              replicas: {{ .Values.proxyConfig.replicas }}
              template:
                spec:
                  tolerations:
                    - effect: "NoSchedule"
                      operator: Exists
                  containers:
                  - name: envoy
                    resources:
                    {{- toYaml .Values.proxyConfig.envoy.resources | nindent 22 }}
                  - name: shutdown-manager
                    resources:
                    {{- toYaml .Values.proxyConfig.shutdownManager.resources | nindent 22 }}
---
