{
 "title": "Kubernetes Deployment metrics",
 "description": "Monitors Kubernetes deployments in cluster using Prometheus. Shows overall cluster CPU / Memory of deployments, replicas in each deployment. Uses Kube state metrics and cAdvisor metrics ",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(machine_memory_bytes{},cluster)"
    }
   },
   {
    "name": "Deployment",
    "query": {
     "query": "label_values(kube_deployment_labels{cluster=~\"$Cluster\"},deployment)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(machine_memory_bytes{cluster=~\"$Cluster\"},kubernetes_io_hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Deployment memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=~\"^$Cluster$\",container!=\"\",id!=\"/\",pod=~\"^$Deployment.*$\",container!=\"POD\"}) / sum (machine_memory_bytes{cluster=~\"^$Cluster$\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Deployment CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{cluster=~\"^$Cluster$\",pod=~\"^$Deployment.*$\",container!=\"POD\"}[1m])) / sum (machine_cpu_cores{cluster=~\"^$Cluster$\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{cluster=~\"^$Cluster$\",deployment=~\"^$Deployment$\",pod_template_hash=\"\"}) / sum(kube_deployment_status_replicas{cluster=~\"^$Cluster$\",deployment=~\"^$Deployment$\",pod_template_hash=\"\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=~\"^$Cluster$\",container!=\"\",id!=\"/\",pod=~\"^$Deployment.*$\",container!=\"POD\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=~\"^$Cluster$\",kubernetes_io_hostname=~\"^$Node.*$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{cluster=~\"^$Cluster$\",pod=~\"^$Deployment.*$\",container!=\"POD\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{cluster=~\"^$Cluster$\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{cluster=~\"^$Cluster$\",deployment=~\"^$Deployment$\",pod_template_hash=\"\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{cluster=~\"^$Cluster$\",deployment=~\"^$Deployment$\",pod_template_hash=\"\"})"
    }
   ]
  },
  {
   "title": "Current Running Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{cluster=~\"^$Cluster$\",pod_template_hash=\"\",deployment=\"$Deployment\"}) by (deployment)",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Deployment CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{cluster=~\"^$Cluster$\",container!=\"\",image!=\"\",pod=~\"^$Deployment.*$\",container!=\"POD\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Containers CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{cluster=~\"^$Cluster$\",image!=\"\",pod=~\"^$Deployment.*$\",container!=\"POD\"}[1m])) by (container, pod)",
     "legendFormat": "pod: {{ pod }} | {{ container }}"
    }
   ]
  },
  {
   "title": "Average no of cores used per min",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{cluster=~\"^$Cluster$\",id!=\"/\",pod=~\"^$Deployment.*$\",container!=\"POD\",container!=\"\"}[1m])) by (container)",
     "legendFormat": "{{ container  }}"
    }
   ]
  },
  {
   "title": "Deployment memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=~\"^$Cluster$\",image!=\"\",pod=~\"^$Deployment.*$\",container!=\"POD\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "All processes memory usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=~\"^$Cluster$\",container!=\"\",id!=\"/\",pod=~\"^$Deployment.*$\",container!=\"POD\"}) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Deployment network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{cluster=~\"^$Cluster$\",container!=\"\",image!=\"\",pod=~\"^$Deployment.*$\",container=\"POD\",}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{cluster=~\"^$Cluster$\",container!=\"\",image!=\"\",name=~\"^k8s_.*\",pod=~\"^$Deployment.*$\",container=\"POD\",}[1m])) by (pod)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{cluster=~\"^$Cluster$\",container!=\"\",id!=\"/\",pod=~\"^$Deployment.*$\",container=\"POD\"}[1m])) by (id)",
     "legendFormat": "{{ id }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{cluster=~\"^$Cluster$\",container!=\"\",id!=\"/\",pod=~\"^$Deployment.*$\",container=\"POD\"}[1m])) by (id)",
     "legendFormat": "<- {{ id }}"
    }
   ]
  }
 ]
}