{
 "title": "Kube Eagle",
 "description": "Overview of all pod & node resource requests, limits and usages",
 "tags": [
  "resources",
  "usage"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(machine_memory_bytes{},cluster)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(eagle_node_resource_allocatable_cpu_cores{cluster=~\"$cluster\"},node)"
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Cores ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "sum(eagle_node_resource_allocatable_cpu_cores{cluster=~\"$cluster\",node=~\"$node\"})",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(eagle_node_resource_requests_cpu_cores{cluster=~\"$cluster\",node=~\"$node\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(eagle_node_resource_limits_cpu_cores{cluster=~\"$cluster\",node=~\"$node\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(eagle_node_resource_usage_cpu_cores{cluster=~\"$cluster\",node=~\"$node\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(eagle_node_resource_usage_cpu_cores{cluster=~\"$cluster\", node=~\"$node\"}) / sum(eagle_node_resource_allocatable_cpu_cores{cluster=~\"$cluster\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(eagle_node_resource_usage_memory_bytes{cluster=~\"$cluster\", node=~\"$node\"}) / sum(eagle_node_resource_allocatable_memory_bytes{cluster=~\"$cluster\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "decbytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(eagle_node_resource_allocatable_memory_bytes{cluster=~\"$cluster\",node=~\"$node\"})",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(eagle_node_resource_requests_memory_bytes{cluster=~\"$cluster\",node=~\"$node\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(eagle_node_resource_limits_memory_bytes{cluster=~\"$cluster\",node=~\"$node\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(eagle_node_resource_usage_memory_bytes{cluster=~\"$cluster\",node=~\"$node\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Node CPU",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(eagle_node_resource_requests_cpu_cores{cluster=~\"$cluster\",node=~\"$node\"}) by (node)"
    },
    {
     "expr": "sum (eagle_node_resource_limits_cpu_cores{cluster=~\"$cluster\",node=~\"$node\"}) by (node)"
    },
    {
     "expr": "sum(eagle_node_resource_allocatable_cpu_cores{cluster=~\"$cluster\",node=~\"$node\"}) by (node)"
    },
    {
     "expr": "sum(eagle_node_resource_requests_cpu_cores{cluster=~\"$cluster\", node=~\"$node\"} / eagle_node_resource_allocatable_cpu_cores{cluster=~\"$cluster\", node=~\"$node\"}) by (node)"
    },
    {
     "expr": "sum(eagle_node_resource_limits_cpu_cores{cluster=~\"$cluster\", node=~\"$node\"} / eagle_node_resource_allocatable_cpu_cores{cluster=~\"$cluster\", node=~\"$node\"}) by (node)"
    },
    {
     "expr": "sum(eagle_node_resource_usage_cpu_cores{cluster=~\"$cluster\", node=~\"$node\"} / eagle_node_resource_allocatable_cpu_cores{cluster=~\"$cluster\", node=~\"$node\"}) by (node)"
    }
   ]
  },
  {
   "title": "Container CPU",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum (eagle_pod_container_resource_requests_cpu_cores{cluster=~\"$cluster\", node=~\"$node\"}) by (pod, container, namespace)"
    },
    {
     "expr": "sum (eagle_pod_container_resource_limits_cpu_cores{cluster=~\"$cluster\", node=~\"$node\"}) by (pod, container, namespace)"
    },
    {
     "expr": "sum (eagle_pod_container_resource_usage_cpu_cores{cluster=~\"$cluster\", node=~\"$node\"}) by (pod, container, namespace)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Node RAM",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(eagle_node_resource_requests_memory_bytes{cluster=~\"$cluster\", node=~\"$node\"}) by (node)"
    },
    {
     "expr": "sum(eagle_node_resource_limits_memory_bytes{cluster=~\"$cluster\", node=~\"$node\"}) by (node)"
    },
    {
     "expr": "sum(eagle_node_resource_allocatable_memory_bytes{cluster=~\"$cluster\", node=~\"$node\"}) by (node)"
    },
    {
     "expr": "sum(eagle_node_resource_requests_memory_bytes{cluster=~\"$cluster\", node=~\"$node\"} / eagle_node_resource_allocatable_memory_bytes{cluster=~\"$cluster\", node=~\"$node\"}) by (node)"
    },
    {
     "expr": "sum(eagle_node_resource_limits_memory_bytes{cluster=~\"$cluster\", node=~\"$node\"} / eagle_node_resource_allocatable_memory_bytes{cluster=~\"$cluster\", node=~\"$node\"}) by (node)"
    },
    {
     "expr": "sum(eagle_node_resource_usage_memory_bytes{cluster=~\"$cluster\", node=~\"$node\"} / eagle_node_resource_allocatable_memory_bytes{cluster=~\"$cluster\", node=~\"$node\"}) by (node)"
    }
   ]
  },
  {
   "title": "Container RAM",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum (eagle_pod_container_resource_requests_memory_bytes{cluster=~\"$cluster\", node=~\"$node\"}) by (pod, container, namespace)"
    },
    {
     "expr": "sum (eagle_pod_container_resource_limits_memory_bytes{cluster=~\"$cluster\", node=~\"$node\"}) by (pod, container, namespace)"
    },
    {
     "expr": "sum (eagle_pod_container_resource_usage_memory_bytes{cluster=~\"$cluster\", node=~\"$node\"}) by (pod, container, namespace)"
    }
   ]
  }
 ]
}