{
 "title": "Kubernetes Pod Metrics",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(machine_memory_bytes{},cluster)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(machine_memory_bytes{cluster=~\"$Cluster\"},kubernetes_io_hostname)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_memory_usage_bytes{cluster=~\"$Cluster\",namespace=~\".+\",container!=\"POD\"},namespace)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(container_memory_usage_bytes{cluster=~\"$Cluster\",namespace=~\"$namespace\",container!=\"POD\"},pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_memory_usage_bytes{cluster=~\"$Cluster\",namespace=~\"$namespace\",container!=\"POD\",pod=\"$Pod\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Container Restarts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container Restarts Increment in 1 hour for $Pod",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{cluster=\"$Cluster\",namespace=\"$namespace\",pod_template_hash=\"\",pod=\"$Pod\",container=\"$container\",container!=\"\"}[1h])  ",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Total Container ( $container ) restarts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{pod_template_hash=\"\",pod=\"$Pod\", container=\"$container\",container!=\"\",cluster=\"$Cluster\"} "
    }
   ]
  },
  {
   "title": "Container ( $container ) Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_running{pod_template_hash=\"\",namespace=\"$namespace\", pod=\"$Pod\",container=\"$container\",container!=\"\",cluster=\"$Cluster\"}"
    }
   ]
  },
  { "title": "Container Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Container ( $container ) Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_last_terminated_reason{namespace=\"$namespace\",container=\"$container\",container!=\"\",cluster=\"$Cluster\",pod_template_hash=\"\",reason=\"Error\"})"
    }
   ]
  },
  {
   "title": "Container ( $container ) OOM Kills",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_last_terminated_reason{namespace=\"$namespace\",container=\"$container\",container!=\"\",cluster=\"$Cluster\",pod_template_hash=\"\",reason=\"OOMKilled\"})"
    }
   ]
  },
  {
   "title": "Container ( $container ) ContainerCannotRun",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_last_terminated_reason{namespace=\"$namespace\",container=\"$container\",container!=\"\",cluster=\"$Cluster\",pod_template_hash=\"\",reason=\"ContainerCannotRun\"})"
    }
   ]
  },
  {
   "title": "Last Termination Reason for $container",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{reason!=\"\", namespace=\"$namespace\",container=\"$container\",container!=\"\",cluster=\"$Cluster\",pod_template_hash=\"\",pod=\"$Pod\"} > 0",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Pod ($Pod ) Waiting Reason",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting_reason{reason!=\"\", namespace=\"$namespace\",pod_template_hash=\"\",pod=\"$Pod\",cluster=\"$Cluster\"} > 0",
     "legendFormat": " {{ container }}  {{ reason }}"
    }
   ]
  },
  { "title": "Total usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Pod memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{container=\"$container\",image!=\"\",pod=\"$Pod\",cluster=\"$Cluster\"}) by (container) / sum(container_spec_memory_limit_bytes{container=\"$container\",image!=\"\",pod=\"$Pod\",cluster=\"$Cluster\"}) by (container) ) * 100"
    }
   ]
  },
  {
   "title": "Pod CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"^$Pod$\",cluster=\"$Cluster\"}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\",cluster=\"$Cluster\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",pod=\"$Pod\",cluster=\"$Cluster\", container=\"$container\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\",cluster=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",pod=\"$Pod\",cluster=\"$Cluster\",container!=\"POD\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{kubernetes_io_hostname=\"$Node\",cluster=\"$Cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "Pod memory working bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",pod=\"$Pod\",cluster=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Persistent Volume Usage (GB)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{cluster=\"$Cluster\",namespace=\"$namespace\"} / (1024*1024*1024)",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Persistent Volume Usage %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{cluster=\"$Cluster\",namespace=\"$namespace\"} / kubelet_volume_stats_capacity_bytes{cluster=\"$Cluster\",namespace=\"$namespace\"} * 100",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Persistent Volume Capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes{cluster=\"$Cluster\",namespace=\"$namespace\"} / (1024*1024*1024)",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  { "title": "Pods CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Pods CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",pod=\"$Pod\",cluster=\"$Cluster\",container!=\"POD\"}[1m])) by (pod)",
     "legendFormat": "{{ $Pod }}"
    }
   ]
  },
  { "title": "All processes CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "All processes CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",pod=\"$Pod\",cluster=\"$Cluster\",container!=\"POD\"}[1m])) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  { "title": "Pods memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",pod=\"$Pod\", cluster=\"$Cluster\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "All processes memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "All processes memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",pod=~\"^$Pod$\",cluster=\"$Cluster\"}) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Cpu usage (relative to limit)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"$container\",container!=\"\",cluster=\"$Cluster\", namespace=\"$namespace\"}[30s])) by (namespace,container) / sum(container_spec_cpu_quota{container=\"$container\",container!=\"\",cluster=\"$Cluster\", namespace=\"$namespace\"} / container_spec_cpu_period{container=\"$container\",container!=\"\",cluster=\"$Cluster\", namespace=\"$namespace\"}) by (namespace,container)",
     "legendFormat": "actual"
    }
   ]
  },
  {
   "title": "Memory usage (relative to limit)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"$container\",image!=\"\",pod=\"$Pod\",cluster=\"$Cluster\"}) by (container) / sum(container_spec_memory_limit_bytes{container=\"$container\",image!=\"\",pod=\"$Pod\",cluster=\"$Cluster\"}) by (container)",
     "legendFormat": "actual"
    }
   ]
  },
  {
   "title": "Cpu usage (per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{image!=\"\",cluster=\"$Cluster\",container!=\"POD\",pod=~\"$Pod\", container=~\"$container\"}[30s])) by (pod,id)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(container_spec_cpu_quota{image!=\"\",pod=\"$Pod\",cluster=\"$Cluster\",container!=\"POD\",container=~\"$container\"} / container_spec_cpu_period{image!=\"\",pod=\"$Pod\",cluster=\"$Cluster\",container!=\"POD\",container=~\"$container\"}) by (namespace,container) / count(container_memory_usage_bytes{image!=\"\",pod=\"$Pod\",cluster=\"$Cluster\",container!=\"POD\",container=~\"$container\"}) by (namespace,container) ",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(container_spec_cpu_shares{image!=\"\",pod=\"$Pod\",cluster=\"$Cluster\",container!=\"POD\",container=~\"$container\"} / 1024) by (namespace,container) / count(container_spec_cpu_shares{image!=\"\",pod=\"$Pod\",cluster=\"$Cluster\",container!=\"POD\",container=~\"$container\"}) by (namespace,container) ",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory usage (per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"$container\",image!=\"\",pod=\"$Pod\",cluster=\"$Cluster\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{container=\"$container\",image!=\"\",pod=\"$Pod\",cluster=\"$Cluster\"}) by (container) / count(container_memory_usage_bytes{container=\"$container\",image!=\"\",pod=\"$Pod\",cluster=\"$Cluster\"}) by (container)",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{container=\"$container\",container!=\"\",cluster=\"$Cluster\", namespace=\"$namespace\"}) by (namespace,container) / count(kube_pod_container_resource_requests_memory_bytes{container=\"$container\",container!=\"\",cluster=\"$Cluster\", namespace=\"$namespace\"}) by (namespace,container)",
     "legendFormat": "request"
    }
   ]
  },
  { "title": "Network I/O pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Network I/O pressure for $Pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{pod=~\"^$Pod$\",cluster=\"$Cluster\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{pod=~\"^$Pod$\",cluster=\"$Cluster\"}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Pods network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Pods network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",pod=\"$Pod\",cluster=\"$Cluster\",container=~\"$container\"}[1m])) by (pod)",
     "legendFormat": "-> {{ pod }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",pod=\"$Pod\",cluster=\"$Cluster\",container=~\"$container\"}[1m])) by (pod)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  },
  { "title": "All processes network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "All processes network I/O",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",pod=~\"^$Pod$\",cluster=\"$Cluster\"}[1m])) by (id)",
     "legendFormat": "-> {{ id }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",pod=~\"^$Pod$\",cluster=\"$Cluster\"}[1m])) by (id)",
     "legendFormat": "<- {{ id }}"
    }
   ]
  }
 ]
}