# Gateway API custom resource state metrics
kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: gateway.networking.k8s.io
        kind: "Gateway"
        version: "v1"
      metricNamePrefix: gatewayapi_gateway
      labelsFromPath:
        name:
        - metadata
        - name
        namespace:
        - metadata
        - namespace
      metrics:
      - name: "info"
        help: "Gateway information"
        each:
          type: Info
          info:
            labelsFromPath:
              gatewayclass_name: [spec, gatewayClassName]
      - name: "labels"
        help: "Kubernetes labels converted to Prometheus labels."
        each:
          type: Info
          info:
            path: [metadata]
            labelsFromPath:
              "*": [labels]
      - name: "created"
        help: "created timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, creationTimestamp]
      - name: "deleted"
        help: "deletion timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, deletionTimestamp]
      - name: "listener_info"
        help: "Gateway listener information"
        each:
          type: Info
          info:
            path: [spec, listeners]
            labelsFromPath:
              listener_name: ["name"]
              port: ["port"]
              protocol: ["protocol"]
              hostname: ["hostname"]
              tls_mode: ["tls","mode"]
              allowed_routes_namespaces_from: ["allowedRoutes", "namespaces", "from"]
      - name: "status"
        help: "status condition"
        each:
          type: Gauge
          gauge:
            path: [status, conditions]
            labelsFromPath:
              type: ["type"]
            valueFrom: ["status"]
      - name: "status_listener_attached_routes"
        help: "Number of attached routes for a listener"
        each:
          type: Gauge
          gauge:
            path: [status, listeners]
            labelsFromPath:
              listener_name: ["name"]
            valueFrom: ["attachedRoutes"]
      - name: "status_address_info"
        help: "Gateway address types and values"
        each:
          type: Info
          info:
            path: [status, addresses]
            labelsFromPath:
              type: ["type"]
              value: ["value"]
    - groupVersionKind:
        group: gateway.networking.k8s.io
        kind: "GatewayClass"
        version: "v1"
      metricNamePrefix: gatewayapi_gatewayclass
      labelsFromPath:
        name:
        - metadata
        - name
      metrics:
      - name: "info"
        help: "GatewayClass information"
        each:
          type: Info
          info:
            labelsFromPath:
              controller_name: [spec, controllerName]
      - name: "labels"
        help: "Kubernetes labels converted to Prometheus labels."
        each:
          type: Info
          info:
            path: [metadata]
            labelsFromPath:
              "*": [labels]
      - name: "created"
        help: "created timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, creationTimestamp]
      - name: "deleted"
        help: "deletion timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, deletionTimestamp]
      - name: "status"
        help: "status condition"
        each:
          type: Gauge
          gauge:
            path: [status, conditions]
            labelsFromPath:
              type: ["type"]
            valueFrom: ["status"]
      - name: "status_supported_features"
        help: "List of supported features for the GatewayClass"
        each:
          type: Info
          info:
            path: [status, supportedFeatures]
            labelsFromPath:
              features: []
    - groupVersionKind:
        group: gateway.networking.k8s.io
        kind: "HTTPRoute"
        version: "v1"
      metricNamePrefix: gatewayapi_httproute
      labelsFromPath:
        name:
        - metadata
        - name
        namespace:
        - metadata
        - namespace
      metrics:
      - name: "labels"
        help: "Kubernetes labels converted to Prometheus labels."
        each:
          type: Info
          info:
            path: [metadata]
            labelsFromPath:
              "*": [labels]
      - name: "created"
        help: "created timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, creationTimestamp]
      - name: "deleted"
        help: "deletion timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, deletionTimestamp]
      - name: "hostname_info"
        help: "Hostname information"
        each:
          type: Info
          info:
            path: [spec, hostnames]
            labelsFromPath:
              hostname: []
      - name: "parent_info"
        help: "Parent references that the httproute wants to be attached to"
        each:
          type: Info
          info:
            path: [spec, parentRefs]
            labelsFromPath:
              parent_group: ["group"]
              parent_kind: ["kind"]
              parent_name: ["name"]
              parent_namespace: ["namespace"]
              parent_section_name: ["sectionName"]
              parent_port: ["port"]
      - name: "status"
        help: "status condition"
        each:
          type: Gauge
          gauge:
            path: [status, parents]
            valueFrom: [conditions, 0, status]
            labelsFromPath:
              type: [conditions, 0, type]
              reason: [conditions, 0, reason]
              message: [conditions, 0, message]
              last_transition_time: [conditions, 0, lastTransitionTime]
              parent_name: [parentRef, name]
              parent_section_name: [parentRef, sectionName]
              controller_name: [controllerName]
      - name: "status_parent_info"
        help: "Parent references that the httproute is attached to"
        each:
          type: Info
          info:
            path: [status, parents]
            labelsFromPath:
              controller_name: ["controllerName"]
              parent_group: ["parentRef", "group"]
              parent_kind: ["parentRef", "kind"]
              parent_name: ["parentRef", "name"]
              parent_namespace: ["parentRef", "namespace"]
              parent_section_name: ["parentRef", "sectionName"]
              parent_port: ["parentRef", "port"]
    - groupVersionKind:
        group: gateway.networking.k8s.io
        kind: "GRPCRoute"
        version: "v1"
      metricNamePrefix: gatewayapi_grpcroute
      labelsFromPath:
        name:
        - metadata
        - name
        namespace:
        - metadata
        - namespace
      metrics:
      - name: "labels"
        help: "Kubernetes labels converted to Prometheus labels."
        each:
          type: Info
          info:
            path: [metadata]
            labelsFromPath:
              "*": [labels]
      - name: "created"
        help: "created timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, creationTimestamp]
      - name: "deleted"
        help: "deletion timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, deletionTimestamp]
      - name: "hostname_info"
        help: "Hostname information"
        each:
          type: Info
          info:
            path: [spec, hostnames]
            labelsFromPath:
              hostname: []
      - name: "status"
        help: "status condition"
        each:
          type: Gauge
          gauge:
            path: [status, parents]
            valueFrom: [conditions, 0, status]
            labelsFromPath:
              type: [conditions, 0, type]
              reason: [conditions, 0, reason]
              message: [conditions, 0, message]
              last_transition_time: [conditions, 0, lastTransitionTime]
              parent_name: [parentRef, name]
              parent_section_name: [parentRef, sectionName]
              controller_name: [controllerName]
      - name: "parent_info"
        help: "Parent references that the grpcroute wants to be attached to"
        each:
          type: Info
          info:
            path: [spec, parentRefs]
            labelsFromPath:
              parent_group: ["group"]
              parent_kind: ["kind"]
              parent_name: ["name"]
              parent_namespace: ["namespace"]
              parent_section_name: ["sectionName"]
              parent_port: ["port"]
      - name: "status_parent_info"
        help: "Parent references that the grpcroute is attached to"
        each:
          type: Info
          info:
            path: [status, parents]
            labelsFromPath:
              controller_name: ["controllerName"]
              parent_group: ["parentRef", "group"]
              parent_kind: ["parentRef", "kind"]
              parent_name: ["parentRef", "name"]
              parent_namespace: ["parentRef", "namespace"]
              parent_section_name: ["parentRef", "sectionName"]
              parent_port: ["parentRef", "port"]
    - groupVersionKind:
        group: gateway.networking.k8s.io
        kind: "TCPRoute"
        version: "v1alpha2"
      metricNamePrefix: gatewayapi_tcproute
      labelsFromPath:
        name:
        - metadata
        - name
        namespace:
        - metadata
        - namespace
      metrics:
      - name: "labels"
        help: "Kubernetes labels converted to Prometheus labels."
        each:
          type: Info
          info:
            path: [metadata]
            labelsFromPath:
              "*": [labels]
      - name: "created"
        help: "created timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, creationTimestamp]
      - name: "deleted"
        help: "deletion timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, deletionTimestamp]
      - name: "parent_info"
        help: "Parent references that the tcproute wants to be attached to"
        each:
          type: Info
          info:
            path: [spec, parentRefs]
            labelsFromPath:
              parent_group: ["group"]
              parent_kind: ["kind"]
              parent_name: ["name"]
              parent_namespace: ["namespace"]
              parent_section_name: ["sectionName"]
              parent_port: ["port"]
      - name: "status_parent_info"
        help: "Parent references that the tcproute is attached to"
        each:
          type: Info
          info:
            path: [status, parents]
            labelsFromPath:
              controller_name: ["controllerName"]
              parent_group: ["parentRef", "group"]
              parent_kind: ["parentRef", "kind"]
              parent_name: ["parentRef", "name"]
              parent_namespace: ["parentRef", "namespace"]
              parent_section_name: ["parentRef", "sectionName"]
              parent_port: ["parentRef", "port"]
      - name: "status"
        help: "status condition"
        each:
          type: Gauge
          gauge:
            path: [status, parents]
            valueFrom: [conditions, 0, status]
            labelsFromPath:
              type: [conditions, 0, type]
              reason: [conditions, 0, reason]
              message: [conditions, 0, message]
              last_transition_time: [conditions, 0, lastTransitionTime]
              parent_name: [parentRef, name]
              parent_section_name: [parentRef, sectionName]
              controller_name: [controllerName]
    - groupVersionKind:
        group: gateway.networking.k8s.io
        kind: "TLSRoute"
        version: "v1alpha2"
      metricNamePrefix: gatewayapi_tlsroute
      labelsFromPath:
        name:
        - metadata
        - name
        namespace:
        - metadata
        - namespace
      metrics:
      - name: "labels"
        help: "Kubernetes labels converted to Prometheus labels."
        each:
          type: Info
          info:
            path: [metadata]
            labelsFromPath:
              "*": [labels]
      - name: "created"
        help: "created timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, creationTimestamp]
      - name: "deleted"
        help: "deletion timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, deletionTimestamp]
      - name: "hostname_info"
        help: "Hostname information"
        each:
          type: Info
          info:
            path: [spec, hostnames]
            labelsFromPath:
              hostname: []
      - name: "parent_info"
        help: "Parent references that the tlsroute wants to be attached to"
        each:
          type: Info
          info:
            path: [spec, parentRefs]
            labelsFromPath:
              parent_group: ["group"]
              parent_kind: ["kind"]
              parent_name: ["name"]
              parent_namespace: ["namespace"]
              parent_section_name: ["sectionName"]
              parent_port: ["port"]
      - name: "status_parent_info"
        help: "Parent references that the tlsroute is attached to"
        each:
          type: Info
          info:
            path: [status, parents]
            labelsFromPath:
              controller_name: ["controllerName"]
              parent_group: ["parentRef", "group"]
              parent_kind: ["parentRef", "kind"]
              parent_name: ["parentRef", "name"]
              parent_namespace: ["parentRef", "namespace"]
              parent_section_name: ["parentRef", "sectionName"]
              parent_port: ["parentRef", "port"]
    - groupVersionKind:
        group: gateway.networking.k8s.io
        kind: "UDPRoute"
        version: "v1alpha2"
      metricNamePrefix: gatewayapi_udproute
      labelsFromPath:
        name:
        - metadata
        - name
        namespace:
        - metadata
        - namespace
      metrics:
      - name: "labels"
        help: "Kubernetes labels converted to Prometheus labels."
        each:
          type: Info
          info:
            path: [metadata]
            labelsFromPath:
              "*": [labels]
      - name: "created"
        help: "created timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, creationTimestamp]
      - name: "deleted"
        help: "deletion timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, deletionTimestamp]
      - name: "parent_info"
        help: "Parent references that the udproute wants to be attached to"
        each:
          type: Info
          info:
            path: [spec, parentRefs]
            labelsFromPath:
              parent_group: ["group"]
              parent_kind: ["kind"]
              parent_name: ["name"]
              parent_namespace: ["namespace"]
              parent_section_name: ["sectionName"]
              parent_port: ["port"]
      - name: "status_parent_info"
        help: "Parent references that the udproute is attached to"
        each:
          type: Info
          info:
            path: [status, parents]
            labelsFromPath:
              controller_name: ["controllerName"]
              parent_group: ["parentRef", "group"]
              parent_kind: ["parentRef", "kind"]
              parent_name: ["parentRef", "name"]
              parent_namespace: ["parentRef", "namespace"]
              parent_section_name: ["parentRef", "sectionName"]
              parent_port: ["parentRef", "port"]
    - groupVersionKind:
        group: gateway.networking.k8s.io
        kind: "BackendTLSPolicy"
        version: "v1alpha3"
      metricNamePrefix: gatewayapi_backendtlspolicy
      labelsFromPath:
        name:
        - metadata
        - name
        namespace:
        - metadata
        - namespace
      metrics:
      - name: "labels"
        help: "Kubernetes labels converted to Prometheus labels."
        each:
          type: Info
          info:
            path: [metadata]
            labelsFromPath:
              "*": [labels]
      - name: "created"
        help: "created timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, creationTimestamp]
      - name: "deleted"
        help: "deletion timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, deletionTimestamp]
      - name: "target_info"
        help: "Target references that the backendtlspolicy wants to be attached to"
        each:
          type: Info
          info:
            path: [spec, targetRef]
            labelsFromPath:
              target_group: ["group"]
              target_kind: ["kind"]
              target_name: ["name"]
              target_namespace: ["namespace"]
