apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: operations
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Operations Project
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    ignore:
    - group: '*'
      kind: '*'
      name: '*'
    warn: true
  sourceRepos:
  - '*'
