{{- if .Values.sealedSecrets.enable -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cluster.name }}-sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  {{- with .Values.sealedSecrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    team: ops
    cluster: {{ .Values.cluster.name }}
spec:
  project: {{ .Values.sealedSecrets.project }}
  source:
    repoURL: {{ .Values.sealedSecrets.source.repoURL }}
    targetRevision: {{ .Values.sealedSecrets.source.targetRevision  | default .Values.source.targetRevision }}
    path: {{ .Values.sealedSecrets.source.path }}
    helm:
      parameters:
        - name: namespace
          value: {{ .Values.sealedSecrets.namespace  }}
      releaseName: {{ tpl .Values.sealedSecrets.source.helm.releaseName . }}
      valueFiles:
      - {{ .Values.sealedSecrets.source.helm.valueFiles | default .Values.source.helm.valueFiles }}
    {{- if .Values.sealedSecrets.source.helm.values }}
      values: {{- toYaml .Values.sealedSecrets.source.helm.values | indent 6 }}
    {{- end }}

  destination:
    {{ if .Values.cluster.server -}}
    server: {{ .Values.cluster.server }}
    {{ else }}
    name: {{ .Values.cluster.name }}
    {{ end -}}
    namespace: {{ .Values.sealedSecrets.namespace  }}

  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
{{- end }}
