{{- if .Values.filebeat.enable -}}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: filebeat
spec:
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
    metadata:
      labels:
        k8s-app: filebeat
    spec:
      tolerations:
        - effect: "NoSchedule"
          operator: Exists
        - effect: "NoExecute"
          operator: Exists
      serviceAccountName: logging
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 30
      containers:
      - name: filebeat
        image: {{ .Values.filebeat.image }}
        args: [
          "-c", "/usr/share/filebeat/filebeat.yml",
          "-e",
        ]
        env:
        - name: ELASTICSEARCH_HOST
          value: "https://{{ .Values.filebeat.es.host }}"
        - name: ELASTICSEARCH_PORT
          value: "{{ .Values.filebeat.es.port }}"
        - name: ELASTICSEARCH_USERNAME
          valueFrom:
            secretKeyRef:
              name: filebeat
              key: elasticsearch_user
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: filebeat
              key: elasticsearch_pass
        - name: K8_CLUSTER_NAME
          value: "{{ .Values.filebeat.clusterName }}"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
          privileged: true
        resources:
          {{ toYaml .Values.filebeat.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /usr/share/filebeat/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - mountPath: /etc/elastic/client/
          name: elastic-client-certs
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: filebeat-config
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
      - name: data
        hostPath:
          path: /var/lib/filebeat-data
          type: DirectoryOrCreate
      - name: elastic-client-certs
        secret:
          defaultMode: 420
          items:
          - key: ca.crt
            path: ca.crt
          - key: client.crt
            path: client.crt
          - key: client.key
            path: client.key
          secretName: elastic-client-certs
          optional: true
---
{{- end }}
