{{- if .Values.filebeat.enable -}}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: filebeat
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    elasticsearch_user: {{ .Values.filebeat.es.username}}
    elasticsearch_pass: {{ .Values.filebeat.es.password }}
  template:
    metadata:
      name: filebeat
      namespace: {{ .Values.namespace }}
    type: Opaque
---
{{- end }}
