apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: elastic-stack
version: 0.1.0
dependencies:
  - name: eck-operator
    version: 0.1.0
    repository: "file://../eck-operator"
    condition: eckOperator.enable
    alias: eckOperator
