{{- if .Values.prometheus.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: {{ .Values.namespace }}
data:
  prometheus.yaml.tmpl: |-
{{ .Files.Get "configs/prometheus-config.yaml" | indent 4 }}
{{- end }}
