---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.thanos.gcs_secret }}
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    thanos-object-storage.yaml: {{ .Values.thanos.gcsSecret }}
  template:
    metadata:
      name: {{ .Values.thanos.gcs_secret }}
      namespace: {{ .Values.namespace }}
    type: Opaque
---
