apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway-deployment
  namespace: monitoring
  labels:
     app: pushgateway
spec:
   replicas: 1
   selector:
     matchLabels:
       app: pushgateway
   template:
      metadata:
         labels:
           app: pushgateway
      spec:
        containers:
         - name: pushgateway
           image: prom/pushgateway
           ports:
           - containerPort: 9091
---
kind: Service
apiVersion: v1
metadata:
  name: pushgateway-service
  namespace: monitoring
spec:
  selector:
    app: pushgateway
  ports:
  - name: pushgateway
    protocol: TCP
    port: 9091
    targetPort: 9091
