apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: es-user-secret
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    ES_PASSWORD: {{ .Values.esSecret.password  }}
    ES_USERNAME: {{ .Values.esSecret.username  }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: es-user-secret
      namespace: {{ .Values.namespace }}
    type: Opaque
