{{ if eq (.Values.jaeger.query.oAuthSidecar.enabled|toString) "true" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: oauth-secret
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    clientId: {{ .Values.oauthSecret.clientId }}
    clientSecret: {{ .Values.oauthSecret.clientSecret }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: oauth-secret
      namespace: {{ .Values.namespace }}
    type: Opaque

{{ end }}
