apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: eck-operator
version: 0.1.0
dependencies:
  - name: eck-operator
    version: 2.16.1
    repository:  https://helm.elastic.co
