{{- if .Values.alertmanager.enabled -}}
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
  labels:
    name: alertmanager
  name: alertmanager
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: alertmanager
  type: {{ .Values.alertmanager.service.type }}
  ports:
  - name: alertmanager
    protocol: TCP
    port: 9093
    targetPort: 9093
{{ end }}
