apiVersion: v2
name: kyverno
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: kyverno
    version: 3.3.9
    repository: https://kyverno.github.io/kyverno/

  - name: policy-reporter
    alias: policyReporter
    version: 3.1.3
    condition: policyReporter.enabled
    repository: https://kyverno.github.io/policy-reporter
