# All manifests relevnat to this policy should be in this file. This include the policy definition, exceptions, reports etc
{{- if .Values.secPolicies.restrictImageRegistries.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-image-registries
  annotations:
    policies.kyverno.io/title: Restrict Image Registries
    policies.kyverno.io/category: Security, Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.26"
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Images from unknown, public registries can be of dubious quality and may not be
      scanned and secured, representing a high degree of risk. Requiring use of known, approved
      registries helps reduce threat exposure by ensuring image pulls only come from them. This
      policy validates that container images only originate from the registry `eu.foo.io` or
      `bar.io`. Use of this policy requires customization to define your allowable registries.      
spec:
  background: true
  webhookConfiguration:
    timeoutSeconds: 30
  rules:
  - name: validate-registries
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      failureAction: {{ .Values.secPolicies.restrictImageRegistries.mode }}
      message: "Unknown image registry."
      pattern:
        spec:
          =(ephemeralContainers):
          - image: "docker.io/service1/* | registry.hub.docker.com/service1/*"
          =(initContainers):
          - image: "docker.io/service1/* | registry.hub.docker.com/service1/*"
          containers:
          - image: "docker.io/service1/* | registry.hub.docker.com/service1/*"

{{- end }}