groups:
 - name: ElasticSearch Alerts
   rules:
   - alert: ElasticSearch Status RED
     annotations:
       summary: "ElasticSearch Status is RED (cluster {{ $labels.cluster }})"
       description: "ES Health is Critical\nCluster Name: {{$externalLabels.cluster}}\nOrchestrator: {{$externalLabels.orchestrator}}"
     expr: |
        elasticsearch_cluster_health_status{color="red"}==1
     for: 3m
     labels:
       team: devops
       severity: critical

   - alert: ElasticSearch Status YELLOW
     annotations:
       summary: "ElasticSearch Status is YELLOW (cluster {{ $labels.cluster }})"
       description: "ES Health is Critical\nCluster Name: {{$externalLabels.cluster}}\nOrchestrator: {{$externalLabels.orchestrator}}"
     expr: |
        elasticsearch_cluster_health_status{color="yellow"}==1
     for: 5m
     labels:
       team: devops
       severity: warning 

   - alert: ElasticSearch Health Missing
     annotations:
       summary: "Last scrape of the ElasticSearch cluster health failed (cluster {{ $labels.cluster }})"
       description: "Last scrape of the ElasticSearch cluster health failed\nCluster Name: {{$externalLabels.cluster}}\nOrchestrator: {{$externalLabels.orchestrator}}"
     expr: |
        elasticsearch_clusterinfo_up !=1
     for: 5m
     labels:
       team: slack
       severity: warning
