{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spinnaker-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: spin-gate
          servicePort: 8084
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: spin-deck
          servicePort: 9000
{{- end }}