apiVersion: v1
kind: Service
metadata:
  labels:
    app: halyard
    role: service
  name: halyard
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: halyard
    role: server
  ports:
  - name: http
    port: 8064
