{{- if .Values.thanos.query.scrape.enabled -}}
---
kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx-metrics
  namespace: ingress-nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '60'
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: ingress-nginx
spec:
  type: LoadBalancer
  selector:
    app: ingress-nginx
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-querier
  name: thanos-query-scrape
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 10901
    protocol: TCP
    targetPort: grpc
    name: grpc
  selector:
    app: thanos-querier
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-secret: "{{ .Values.namespace }}/query-ingress-tls"
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/ttl: "5"
  name: query-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: {{ .Values.thanos.query.scrape.host }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: thanos-query-scrape
            port:
              name: grpc

  tls:
  - hosts:
    - {{ .Values.thanos.query.scrape.host }}
    secretName: query-ingress-tls
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: query-ingress-tls
  namespace: {{ .Values.namespace }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    ca.crt: {{ .Values.thanos.query.scrape.ingressTls.ca_crt }}
    tls.crt: {{ .Values.thanos.query.scrape.ingressTls.tls_crt }}
    tls.key: {{ .Values.thanos.query.scrape.ingressTls.tls_key }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: query-ingress-tls
      namespace: {{ .Values.namespace }}
    type: Opaque
---
{{- end }}
